# Sleep Coordinator for Home Assistant Integration
# Ensures sensors complete readings before Home Assistant triggers sleep
# Coordinates with HA automation for optimal battery life

# Global variables for sleep coordination
globals:
  # Sleep readiness flag
  - id: sleep_ready
    type: bool
    restore_value: false
    initial_value: 'false'

  # Wake timestamp for timeout protection
  - id: wake_timestamp
    type: int
    restore_value: false
    initial_value: '0'

# Binary sensor to signal Home Assistant when ready for sleep
binary_sensor:
  # Sleep ready signal for Home Assistant automation
  - platform: template
    name: "Sleep Ready"
    id: sleep_ready_signal
    device_class: "running"
    lambda: |-
      return id(sleep_ready);
    on_press:
      # When sleep becomes ready, publish MQTT message for HA
      - mqtt.publish:
          topic: "mykomonitor/myko-monitor-ii-${device_name_suffix}/sleep_ready"
          payload: "true"
          retain: false

# Script to check if all sensors are ready for sleep
script:
  - id: check_sleep_readiness
    then:
      - lambda: |-
          // Check if sensors have state (readings available)
          bool co2_ready = id(co2sensor).has_state();
          bool sht35_ready = id(sht35_sensor).has_state();

          bool all_sensors_ready = co2_ready && sht35_ready;

          if (all_sensors_ready && !id(sleep_ready)) {
            ESP_LOGI("sleep_coord", "All sensors complete - signaling sleep ready");
            id(sleep_ready) = true;
            id(sleep_ready_signal).publish_state(true);
          }

# Wake cycle initialization
esphome:
  on_boot:
    priority: 600  # Run early in boot sequence
    then:
      - lambda: |-
          // Initialize wake cycle
          id(wake_timestamp) = millis() / 1000;
          id(sleep_ready) = false;

          ESP_LOGI("sleep_coord", "Wake cycle started - waiting for sensor readings");

# Periodic checks for sleep readiness
interval:
  # Check every 5 seconds if sensors are ready
  - interval: 5s
    then:
      - script.execute: check_sleep_readiness

# Safety timeout to prevent infinite wake
  # Force sleep readiness after maximum wake time (5 minutes)
  - interval: 5min
    then:
      - lambda: |-
          if (!id(sleep_ready)) {
            ESP_LOGW("sleep_coord", "Wake timeout - forcing sleep ready signal");
            id(sleep_ready) = true;
            id(sleep_ready_signal).publish_state(true);
          }

# MQTT sleep command handler with coordination
mqtt:
  on_message:
    # Enhanced sleep command with readiness check
    - topic: mykomonitor/myko-monitor-ii-${device_name_suffix}/command/sleep
      then:
        - lambda: |-
            ESP_LOGI("sleep_coord", "Sleep command received from Home Assistant");
            
            // Check if sensors are ready
            if (id(sleep_ready)) {
              ESP_LOGI("sleep_coord", "Sensors ready - entering deep sleep immediately");
              id(deep_sleep_1).begin_sleep();
            } else {
              ESP_LOGW("sleep_coord", "Sensors not ready - waiting 30s then forcing sleep");
              // Wait briefly for sensors, then force sleep
            }
    
    # Immediate forced sleep command (emergency)
    - topic: mykomonitor/myko-monitor-ii-${device_name_suffix}/command/force_sleep
      then:
        - lambda: |-
            ESP_LOGW("sleep_coord", "Forced sleep command - entering deep sleep immediately");
            id(deep_sleep_1).begin_sleep();

# Status reporting for Home Assistant integration
sensor:
  # Wake duration for monitoring
  - platform: template
    name: "Wake Duration"
    id: wake_duration
    unit_of_measurement: "s"
    state_class: "measurement"
    entity_category: "diagnostic"
    update_interval: 30s
    lambda: |-
      return (millis() / 1000) - id(wake_timestamp);
  
  # Sensors completion status (based on sensor state availability)
  - platform: template
    name: "Sensors Ready"
    id: sensors_ready_count
    state_class: "measurement"
    entity_category: "diagnostic"
    update_interval: 15s
    lambda: |-
      int ready_count = 0;
      if (id(co2sensor).has_state()) ready_count++;
      if (id(sht35_sensor).has_state()) ready_count++;
      return ready_count;

# Home Assistant automation example (for documentation)
# Add this to your Home Assistant automations.yaml:
#
# - alias: "Myko Monitor Sleep Control"
#   trigger:
#     - platform: mqtt
#       topic: "mykomonitor/myko-monitor-ii-+/sleep_ready"
#       payload: "true"
#   action:
#     - service: mqtt.publish
#       data:
#         topic: "mykomonitor/myko-monitor-ii-{{ trigger.topic.split('/')[1] }}/command/sleep"
#         payload: "sleep"
#   mode: single