esphome:
  name: myko-monitor-ii-${device_name_suffix}
  friendly_name: Myko Monitor II.${device_name_suffix}
  project:
    name: "vdwals.mykomonitor"
    version: "2.2.2"
  name_add_mac_suffix: False

# Enable logging
logger:
  baud_rate: 0
  level: INFO