# ESPHome Base Configuration - DEPRECATED
#
# IMPORTANT: This file is deprecated in favor of specific base configurations:
#
#   - base-mains.yml    : For mains-powered devices (NO battery monitoring)
#   - base-battery.yml  : For battery-powered devices (WITH battery monitoring)
#
# Please use one of the specific configurations above instead of this file.
# This file now defaults to base-mains.yml for backward compatibility.

# For backward compatibility, include base-mains.yml
packages:
  base_mains: !include base-mains.yml