# ESPHome Core Configuration
# Common modules shared between mains-powered and battery-powered configurations
# This file should not be used directly - include it in base-mains.yml or base-battery.yml

esphome:
  # Device naming using substitution variables
  # ${device_name_suffix} should be defined in device-specific configs
  name: myko-monitor-ii-${device_name_suffix}
  friendly_name: Myko Monitor II.${device_name_suffix}

  # Project metadata for ESPHome dashboard and updates
  project:
    name: "vdwals.mykomonitor"
    version: "2.5.0"

  # Disable MAC suffix to use predictable device names
  name_add_mac_suffix: False

# Modular package system - common modules for all device types
packages:
  # CO2 sensor configuration - MH-Z16/MH-Z19 via UART
  mh_z16: !include modules/mh-z16.yml

  # Temperature/humidity sensor - SHT35 via I2C
  sht35: !include modules/sht35.yml

  # Status LED indicators for device state
  status_led: !include modules/status_led.yml

  # WiFi connectivity with power optimization
  wifi: !include modules/wifi.yml

  # MQTT messaging for data transmission (core functionality)
  mqtt: !include modules/mqtt-core.yml

  # Logging configuration with power-aware settings
  logger: !include modules/logger.yml
