esphome:
  name: myko-monitor-ii-${device_name_suffix}
  friendly_name: Myko Monitor II.${device_name_suffix}
  project:
    name: "vdwals.mykomonitor"
    version: "2.3.2"
  name_add_mac_suffix: False

packages:
  deep_sleep: !include deep_sleep.yml
  logger: !include logger.yml