uart:
  rx_pin: ${mh_z16_rx}
  tx_pin: ${mh_z16_tx}
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: co2sensor
    co2:
      name: "CO₂ Wert"
    temperature:
      name: "CO₂-Sensor Temperatur"
      entity_category: "diagnostic"
    update_interval: ${update_interval}
    automatic_baseline_calibration: false
    warmup_time: 3min

button:
  - platform: template
    name: "Kalibrieren"
    on_press:
      - mhz19.calibrate_zero: co2sensor