esphome:
  name: co2-markii
  friendly_name: co2_markII
  project:
    name: "vdwals.co2sensor"
    version: "1.1.0"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "8MEXGt88rxOA+J5h2y5O/rpz7BFz8KtO6MhTiaEeI3E="

ota:
  platform: esphome
  password: "aa85749b46e069f3afc7b5e18ba93a0c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: co2sensor2.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Co2-Markii"
    password: "yXx9WnWnW28t"

## Status LED for Issues
status_led:
  pin: GPIO14

uart:
  rx_pin: 13
  tx_pin: 15
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: co2sensor_markII_001
    co2:
      name: "MH-Z16 CO2 Value"
    temperature:
      name: "MH-Z16 Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false
    warmup_time: 3min

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

button:
  - platform: template
    name: "Kalibrieren"
    on_press:
      - mhz19.calibrate_zero: co2sensor_markII_001

captive_portal:
    