esphome:
  name: co2-marki
  friendly_name: co2_markI
  project:
    name: "vdwals.co2sensor"
    version: "1.1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "obMQnwWmCq5jmBaBqMnWBnecSyC4E7IDsmt3jwnZPAI="

ota:
  platform: esphome
  password: "6521380daa1d5c400aace1c1064be43a"

wifi:
  ssid: Myzel-Netzwerk
  password: xxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Co2-Mark I"
    password: "CPHAz14LIGdv"

captive_portal:

uart:
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: co2sensor_markI_001
    co2:
      name: "MH-Z16 CO2 Value"
    temperature:
      name: "MH-Z16 Temperature"
      entity_category: "diagnostic"
    update_interval: 60s
    automatic_baseline_calibration: false
    warmup_time: 3min

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

button:
  - platform: template
    name: "Kalibrieren"
    on_press:
      - mhz19.calibrate_zero: co2sensor_markI_001