substitutions:
  sda_pin: GPIO4
  scl_pin: GPIO5

i2c:
  sda: ${sda_pin}
  scl: ${scl_pin}
  scan: true

sensor:
  - platform: sht3xd
    id: sht35_sensor
    temperature:
      name: "Temperatur"
      state_class: "measurement"
    humidity:
      name: "Luftfeuchtigkeit"
      state_class: "measurement"
    address: ${sht_35_address}
    update_interval: ${update_interval}