i2c:
  sda: GPIO5
  scl: GPIO4
  scan: false

sensor:
  - platform: sht3xd
    temperature:
      name: "Temperatur"
    humidity:
      name: "Luftfeuchtigkeit"
    address: ${sht_35_address}
    update_interval: ${update_interval}