substitutions:
  wifi_power: "20.5db"

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  output_power: ${wifi_power}

  # Faster Connection, reducing required power
  fast_connect: true
  manual_ip:
    static_ip: 192.168.11.65
    gateway: 192.168.11.1
    subnet: 255.255.255.0

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""